### ISSUE TITLE
Dates are not recognized

### ISSUE THREAD

**Issue by AustinLeligdon** [n1tr0-5urf3r/whatsapp_analyzer#1]
In line 8 there is a TODO to fix dates and newlines, currently the script doesn't work as it does not recognize dates.

```
Traceback (most recent call last):
    File "analyzer.py", line 146, in <module>
        print("Nachrichten seit {}".format(first_date))
NameError: name 'first_date' is not defined
```

**Comment by n1tr0-5urf3r** [comment]
It's still working for me, maybe the layout of .txt exports in other languages than german looks different? 
Mine is like _"05.10.17, 20:43 - Name: Messagetext"_

I also changed it a bit so that system messages like "using encryption..." get ignored now

**Comment by AustinLeligdon** [comment]
So I did have to change the dates from "05/10/17" to "05.10.17", but the issues actually was that on some lines the message carries over. I think it's when I have a new line in the message so then there is no date for that line and it crashes the program. So I have to go through by hand and fix all of those instances, but it will probably fix the issues I'm having. Thanks!
